Revert "04_wrl_buildtools.sh: update buildtools to 10.22.33.6"
This reverts commit 8114127287d33fa9fbe7780d08bfaa590b978345.

Failed to build:
Exception:   File "/path/to/buildtools.buildtools-standalone-10.22.33.6/sysroots/x86_64-wrlinuxsdk-linux/usr/lib/python3.10/site-packages/git/remote.py", line 700
    url = Git.polish_url(url)
IndentationError: unexpected indent

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>