Revert "meta-virtualization-dl-3-4.xml: Remove obsoloted git repos"
Issue: LINCD-6774

This reverts commit 2ff0ac20d01bf41fa7655174adff2de51d1039d8 to fix
below error:
ERROR: podman-3.3.1-r0 do_fetch: Network access disabled through BB_NO_NETWORK (or set indirectly due to use of BB_FETCH_PREMIRRORONLY) but access requested with command LANG=C git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false clone --bare --mirror git://github.com/containers/podman.git /build/downloads/git2/github.com.containers.podman.git --progress (for url git://github.com/containers/podman.git;branch=v3.3)

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>