Revert "04_wrl_buildtools.sh: update buildtools to 10.22.33.6a"
This reverts commit c4e82068faf18d506e3e9eb76be61f484c707331.

Reverted since IndentationError:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>

    url = Git.polish_url(url)
IndentationError: unexpected indent

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>